#开发环境配置

server:
  port: 9092

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: zhaobao
    password: x5219438

# 开启权限拦截
auth:
  enabled: true

# 开启http请求日志记录
request-log:
  enabled: true

#日志配置
logging:
  level:
    # web信息日志等级
    web: debug
    # SQL日志记录
    com.zb.misscmszb.mapper: debug