#文件上传配置

cms:
  file:
    # 文件上传后，访问域名配置
    domain: http://localhost:9092/
    # 禁止某些类型文件上传
    exclude:
    # 允许某些类型文件上传
    include:
      - .jpg
      - .png
      - .jpeg
    # 上传文件最大数量
    nums: 10
    # 服务器文件路径
    serve-path: assets/**
    # 单个文件最大体积
    single-limit: 2MB
    # 本地文件存储位置，默认在工作目录下的assets目录
    store-dir: assets/
spring:
  servlet:
    multipart:
      # 总体文件最大体积（只能从max-file-size设置总体文件的大小）
      max-file-size: 20MB